print("hello World")
print("Première modification !")
print("Le mot cerne est masculin")
print("7 est mon chiffre favori !")
print("- Y a une vie après la mort ? - Non c'est l'inverse, y a une mort après la vie")
